
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class panggilankaryawan extends javax.swing.JFrame {

    /**
     * Creates new form panggilankaryawan
     */
    
    public static int gajiPokok, bonusLembur, kehadiran, hutang, potongan, tunjangan, totalDiterima;
    public static double pph;
    public static String tanggal;
    public static String kodeGaji, kodeKaryawan, nama, alamat, telp, jabatan;
    
    DefaultTableModel model = new DefaultTableModel();
    
    public panggilankaryawan() {
        initComponents();
        koneksi.koneksi();
        header();
        reload();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tanggalPenggajian = new javax.swing.JTextField();
        KodeKaryawan = new javax.swing.JTextField();
        NamaKaryawan = new javax.swing.JTextField();
        notlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        txt_jabatan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Gajipokok = new javax.swing.JTextField();
        Bonuslembur = new javax.swing.JTextField();
        Hutang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pph = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Potongan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Tunjangan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        totalditerima = new javax.swing.JTextField();
        cmb_kodeGaji = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setText("Kode Gaji");

        jLabel2.setText("Tgl Pengajian");

        jLabel3.setText("Kode karyawan");

        jLabel4.setText("Nama Karyawan");

        jLabel5.setText("Alamat");

        jLabel6.setText("No. Telp");

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel7.setText("Gaji Pokok");

        jLabel8.setText("Bonus lembur");

        jLabel10.setText("Hutang");

        Gajipokok.setEditable(false);

        Bonuslembur.setEditable(false);

        jLabel11.setText("PPH");

        Pph.setEditable(false);

        jLabel12.setText("Potongan");

        jLabel13.setText("Tunjangan");

        Tunjangan.setEditable(false);

        jLabel14.setText("Total Diterima");

        totalditerima.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Bonuslembur, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addComponent(Gajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pph)
                    .addComponent(Potongan)
                    .addComponent(Tunjangan)
                    .addComponent(totalditerima, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Gajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Pph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Bonuslembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Potongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(Hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(Tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalditerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmb_kodeGaji.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----- Pilih Kode -----", "K-001", "K-002", "K-003", "K-004" }));

        jButton1.setText("cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Detail Gaji");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel16.setText("Jabatan");

        btn_hapus.setText("Hapus");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(notlp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txt_jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(KodeKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(NamaKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(cmb_kodeGaji, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_tanggalPenggajian)
                                    .addComponent(jScrollPane1))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_simpan)
                                        .addGap(28, 28, 28)
                                        .addComponent(btn_ubah)
                                        .addGap(27, 27, 27)
                                        .addComponent(btn_hapus)
                                        .addGap(26, 26, 26)
                                        .addComponent(keluar))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 247, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmb_kodeGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tanggalPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(KodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(btn_simpan)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(keluar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(notlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        cmb_kodeGaji.setSelectedIndex(0);
        txt_tanggalPenggajian.setText("");
        KodeKaryawan.setText("");
        NamaKaryawan.setText("");
        Alamat.setText("");
        notlp.setText("");
        txt_jabatan.setText("");
        Gajipokok.setText("");
        Bonuslembur.setText("");
        Hutang.setText("");
        Pph.setText("");
        Potongan.setText("");
        Tunjangan.setText("");
        totalditerima.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(Hutang.getText().equals("")||Potongan.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Hutang dan Potongan harus diisi..");
            }
            else{
                if(cmb_kodeGaji.getSelectedItem().equals("K-001")){
                gajiPokok = 1500000;
                bonusLembur = 100000;
                //kehadiran = 
                //hutang = 

                //potongan = 
                tunjangan = 100000;
                }
                else if(cmb_kodeGaji.getSelectedItem().equals("K-002")){
                    gajiPokok = 1500000;
                    bonusLembur = 100000;
                    tunjangan = 100000;
                }
                else if(cmb_kodeGaji.getSelectedItem().equals("K-003")){
                    gajiPokok = 2000000;
                    bonusLembur = 150000;
                    tunjangan = 150000;
                }
                else if(cmb_kodeGaji.getSelectedItem().equals("K-004")){
                    gajiPokok = 2500000;
                    bonusLembur = 200000; 
                    tunjangan = 200000;
                }
                pph = 0.05*gajiPokok;
                
                Gajipokok.setText(String.valueOf(gajiPokok));
                Bonuslembur.setText(String.valueOf(bonusLembur));
                Tunjangan.setText(String.valueOf(tunjangan));
                //Hutang.setText(String.valueOf(hutang));
                Pph.setText(String.valueOf(pph));
                hutang = Integer.valueOf(Hutang.getText());
                potongan = Integer.valueOf(Potongan.getText());
                totalDiterima = gajiPokok+bonusLembur+tunjangan-hutang-(int)pph-potongan;
                totalditerima.setText(""+totalDiterima);
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        //ResultSet rs 
        kodeGaji = cmb_kodeGaji.getSelectedItem().toString();
        tanggal = txt_tanggalPenggajian.getText();
        kodeKaryawan = KodeKaryawan.getText();
        nama = NamaKaryawan.getText();
        alamat = Alamat.getText();
        telp = notlp.getText();
        jabatan = txt_jabatan.getText();
        
        //JOptionPane.showMessageDialog(null, kodeGaji+"\n"+tanggal+"\n"+kodeKaryawan+"\n"+nama+"\n"+alamat+"\n"+telp+"\n"+jabatan+"\n"+gajiPokok+"\n"+bonusLembur+"\n"+hutang+"\n"+pph+"\n"+potongan+"\n"+tunjangan+"\n"+totalDiterima);
        try{
            String query = "INSERT INTO tb_kar values('"+kodeGaji+"','"+tanggal+"','"+kodeKaryawan+"','"+nama+"','"+alamat+"','"+telp+"','"+jabatan+"','"+gajiPokok+"','"+bonusLembur+"','"+hutang+"','"+pph+"','"+potongan+"','"+tunjangan+"','"+totalDiterima+"')";
            koneksi.st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Pengisian Data Berhasil" );
        }
        catch(Exception z){
            JOptionPane.showMessageDialog(null,"Pengisian Data Gagal\n" + z);
        }
        
        reload();
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try{
            String query = "UPDATE tb_kar SET kodeGaji='"+kodeGaji+"',tgl='"+tanggal+"',kodeKaryawan='"+kodeKaryawan+"',namaKaryawan='"+nama+"',alamat='"+alamat+"',telp='"+telp+"',jabatan='"+jabatan+"',gajiPokok='"+gajiPokok+"',bonusLembur='"+bonusLembur+"',hutang='"+hutang+"',pph='"+pph+"',potongan='"+potongan+"',tunjangan='"+tunjangan+"',total='"+totalDiterima+"'where kodeKaryawan = '"+kodeKaryawan+"'";
            koneksi.st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Ubah Data Berhasil" );
        }
        catch(Exception z){
            JOptionPane.showMessageDialog(null,"Ubah Data Gagal\n" + z);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panggilankaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panggilankaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panggilankaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panggilankaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panggilankaryawan().setVisible(true);
            }
        });
    }
    
    void header(){
        model = new DefaultTableModel();
        model.addColumn("Kode Gaji");
        model.addColumn("Tanggal Penggajian");
        model.addColumn("Kode Karyawan");
        model.addColumn("Nama Karyawan");
        model.addColumn("Alamat");
        model.addColumn("No Telp");
        model.addColumn("Jabatan");
        model.addColumn("Gaji Pokok");
        model.addColumn("Bonus Lembur");
        model.addColumn("Hutang");
        model.addColumn("PPH");
        model.addColumn("Potongan");
        model.addColumn("Tunjangan");
        model.addColumn("Total");
        jTable1.setModel(model);
    }
    
    public ArrayList reload(){
        model.getDataVector().removeAllElements();
        ArrayList a = new ArrayList();
        
        koneksi.koneksi();
        try {
            ResultSet rst = koneksi.st.executeQuery("SELECT * from tb_kar");
            while(rst.next()){
                Object[] data = new Object[14];
                
                data[0] = rst.getString(1);
                data[1] = rst.getString(2);
                data[2] = rst.getString(3);
                data[3] = rst.getString(4);
                data[4] = rst.getString(5);
                data[5] = rst.getString(6);
                data[6] = rst.getString(7);
                data[7] = rst.getString(8);
                data[8] = rst.getString(9);
                data[9] = rst.getString(10);
                data[10] = rst.getString(11);
                data[11] = rst.getString(12);
                data[12] = rst.getString(13);
                data[13] = rst.getString(14);
                model.addRow(data);
            }
        } catch (Exception e) {
        }
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Bonuslembur;
    private javax.swing.JTextField Gajipokok;
    private javax.swing.JTextField Hutang;
    private javax.swing.JTextField KodeKaryawan;
    private javax.swing.JTextField NamaKaryawan;
    private javax.swing.JTextField Potongan;
    private javax.swing.JTextField Pph;
    private javax.swing.JTextField Tunjangan;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cmb_kodeGaji;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField notlp;
    private javax.swing.JButton reset;
    private javax.swing.JTextField totalditerima;
    private javax.swing.JTextField txt_jabatan;
    private javax.swing.JTextField txt_tanggalPenggajian;
    // End of variables declaration//GEN-END:variables
}
